name: pictaboo
description: A Flutter version of Pict-A-Boo
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path_provider: ^2.1.1
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  camera: ^0.11.0+1
  image_picker: ^1.1.0
  image: ^4.2.0
  path: ^1.8.3
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/frames/
    - assets/welcome/
    - assets/icons/
